spring:
  application:
    name: authentication-api
---
server:
  port: 8084
  http2:
    enabled: true
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:security/server-keystore.jks
    key-store-type: JCEKS
    key-store-password: changeit
    key-alias: authentication-api
    trust-store: classpath:security/server-truststore.jks
    trust-store-type: JCEKS
    trust-store-password: changeit

jwt:
  secret: 4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n

accounts-api:
  url-accounts: https://localhost:8444/accounts