spring:
  application:
    name: authentication-api
---
server:
  port: 8090

security:
  signing-key: MaYzkSjmkzPC57L
  security-realm: Authentication API Realm

jwt:
  secret: 4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n4ut3nt1c4t10n
