spring:
  application:
    name: authentication-api
---
server:
  port: 8444
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:security/server-keystore.jks
    key-store-type: JCEKS
    key-store-password: changeit
    key-alias: authentication-api
    trust-store: classpath:security/server-truststore.jks
    trust-store-type: JCEKS
    trust-store-password: changeit

security:
  require-ssl: true
  signing-key: MaYzkSjmkzPC57L
  security-realm: Authentication API Realm
  jwt:
    client-id: testjwtclientid
    client-secret: XY7kmzoNzl100
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: testjwtresourceid